config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"
  resources :lessons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  mount_uploader :lesson_doc, LessonDocUploader

  validates :title, :content, :lesson_doc, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :load_lesson, only: %i(show edit update destroy)

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new lesson_params
    if @lesson.save
      flash[:success] = "Create lesson success"
      redirect_to lesson_path(@lesson)
    else
      flash.now[:danger] = "Create lesson fail"
      render :new
    end
  end

  def index
    @lessons = Lesson.all
  end

  def show
  end

  def edit
  end

  def update
    if @lesson.update_attributes lesson_params
      flash[:success] = "Update lesson success"
      redirect_to lesson_path(@lesson)
    else
      flash.now[:danger] = "Update lesson fail"
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    flash[:success] = "Delete lesson success"
    redirect_to root_url
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :content).merge lesson_doc: lesson_doc
  end

  def lesson_doc
    params[:lesson][:lesson_doc] || File.open(params[:lesson][:lesson_doc_url])
  end

  def load_lesson
    @lesson = Lesson.find_by id: params[:id]
    return if @lesson

    flash[:danger] = "Lesson not found"
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message record, attribute
    record.errors.to_hash(true)[attribute]&.first
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoUploadPdf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for lesson, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
      <span class="text-danger"><%= error_message lesson, :title %></span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: "form-control" %>
      <span class="text-danger"><%= error_message lesson, :content %></span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :lesson_doc, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.file_field :lesson_doc, class: "form-control js-file-pdf" %>
      <span class="text-danger"><%= error_message lesson, :lesson_doc %></span><br>

      <embed class="js-preview-pdf" src="<%= lesson.lesson_doc.url %>" width="100%" height="500px" type="application/pdf"/>
      <%= hidden_field :lesson, :lesson_doc_url, value: lesson.lesson_doc.path %>
    </div>
  </div>

  <div class="form-group">        
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<tr>
  <td><%= lesson.id %></td>
  <td><%= lesson.title %></td>
  <td>
    <%= link_to lesson_path(lesson), class: "btn btn-sm btn-primary" do %>
      <span class="glyphicon glyphicon-eye-open"></span>
    <% end %>
    <%= link_to edit_lesson_path(lesson), class: "btn btn-sm btn-success" do %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    <%= link_to lesson_path(lesson), method: :delete, class: "btn btn-sm btn-danger" do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
</tr>

app/views/lessons/edit.html.erb
<div class="container">
  <h2>Update Lesson</h2>

  <%= render "form", lesson: @lesson %>
</div>

app/views/lessons/index.html.erb
<div class="container">
  <h2>Lesson List</h2>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "lesson", collection: @lessons %>
    </tbody>
  </table>
</div>

app/views/lessons/new.html.erb
<div class="container">
  <h2>Create Lesson</h2>

  <%= render "form", lesson: @lesson %>
</div>

app/views/lessons/show.html.erb
<div class="container">
  <h2><%= @lesson.title %></h2>

  <div>
    <h4>Content</h4>
    <p><%= @lesson.content %></p>
  </div>

  <% if @lesson.lesson_doc.file %>
    <div>
      <h4>Lesson Doc</h4>
      <embed src="<%= @lesson.lesson_doc.url %>" width="100%" height="500px" />
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= type.capitalize %></strong> <%= message %>
  </div>
<% end %>